#! /bin/sh
#
# This is /sbin/ykluks-keyscript, which gets called when unlocking the disk
#
YUBIKEY_LUKS_SLOT=2 #Set this in case the value is missing in /etc/ykluks.cfg

. /etc/ykluks.cfg

if [ -z "$WELCOME_TEXT" ]; then
    WELCOME_TEXT="Please insert yubikey and press enter or enter a valid passphrase"
fi

message()
{
    if [ -x /bin/plymouth ] && plymouth --ping; then
        plymouth message --text="$*"
    else
        echo "$@" >&2
    fi
    return 0
}

check_yubikey_present="$(ykinfo -q -"$YUBIKEY_LUKS_SLOT" 2>/dev/null)"

if [ -z "$cryptkeyscript" ]; then
    if [ -x /bin/plymouth ] && plymouth --ping; then
        cryptkeyscript="plymouth ask-for-password --prompt"
    else
        cryptkeyscript="/lib/cryptsetup/askpass"
    fi
fi

if [ "$check_yubikey_present" = "1" ]; then
    PW="$($cryptkeyscript 'Yubikey detected, enter appropriate passphrase')"
else
    PW="$($cryptkeyscript 'No Yubikey detected, enter full passphrase')"
fi

if [ "$check_yubikey_present" = "1" ]; then
  if [ "$YUBIKEY_COUNT" -ne "1" ] && [ "$(echo $PW | cut -c1-1)" = "$MULTI_KEY_PREFIX" ]; then
      PW="$(echo "$PW" | cut -c2-)"
      PASSWORD=""
      for i in $(seq 1 $YUBIKEY_COUNT); do
          message "Accessing Yubikey $i..."
          if [ "$HASH" = "1" ]; then
              PW=$(printf %s "$PW" | sha256sum | awk '{print $1}')
          fi
          R="$(printf %s "$PW" | ykchalresp -"$YUBIKEY_LUKS_SLOT" -i- 2>/dev/null || true)"
          if [ "$R" ]; then
              PASSWORD="$PASSWORD$R"
          else
              message "Failed to retrieve response from the Yubikey"
          fi

          if [ "$i" -ne "$YUBIKEY_COUNT" ]; then
              message "Remove the inserted Yubikey"
              while true; do
                  check_yubikey_present="$(ykinfo -q -"$YUBIKEY_LUKS_SLOT" 2>/dev/null)"
                  if [ "$check_yubikey_present" != "1" ]; then
                      break
                  fi
              done

              message "Insert the next Yubikey"
              while true; do
                  check_yubikey_present="$(ykinfo -q -"$YUBIKEY_LUKS_SLOT" 2>/dev/null)"
                  if [ "$check_yubikey_present" = "1" ]; then
                      break
                  fi
              done

              PW="$($cryptkeyscript "Enter the next password")"
          fi
      done
      printf '%s' "$PASSWORD"
  else
      message "Accessing yubikey..."
      if [ "$HASH" = "1" ]; then
          PW=$(printf %s "$PW" | sha256sum | awk '{print $1}')
      fi
      R="$(printf %s "$PW" | ykchalresp -"$YUBIKEY_LUKS_SLOT" -i- 2>/dev/null || true)"
      if [ "$R" ]; then
          message "Retrieved the response from the Yubikey"
          if [ "$CONCATENATE" = "1" ]; then
              printf '%s' "$PW$R"
          else
              printf '%s' "$R"
          fi
      else
          message "Failed to retrieve the response from the Yubikey"
      fi
  fi
else
        printf '%s' "$PW"
fi

exit 0
